services:
  classes:
    ports:
     - ${CLASSES_EXTERNAL_DEBUG_PORT}:${CLASSES_INTERNAL_DEBUG_PORT}
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${CLASSES_INTERNAL_DEBUG_PORT} -jar /app/target/classes-service-0.0.1-SNAPSHOT.jar